
/**
 * Mock Kalshi event data for testing.
 */
export const eventMockData = {
  "markets": [
    {
      "ticker": "KXHIGHNY-26JAN10-T70",
      "event_ticker": "KXHIGHNY-26JAN10",
      "market_type": "binary",
      "title": "Will the high temperature in NYC be at least 70°F on January 10, 2026?",
      "subtitle": "High temperature ≥ 70°F",
      "yes_sub_title": "High temp ≥ 70°F",
      "no_sub_title": "High temp < 70°F",
      "created_time": "2023-11-07T05:31:56Z",
      "open_time": "2023-11-07T05:31:56Z",
      "close_time": "2026-01-10T23:59:59Z",
      "expiration_time": "2026-01-11T05:00:00Z",
      "latest_expiration_time": "2026-01-11T05:00:00Z",
      "settlement_timer_seconds": 3600,
      "status": "active",
      "response_price_units": "usd_cent",
      "yes_bid": 15,
      "yes_bid_dollars": "0.15",
      "yes_ask": 18,
      "yes_ask_dollars": "0.18",
      "no_bid": 82,
      "no_bid_dollars": "0.82",
      "no_ask": 85,
      "no_ask_dollars": "0.85",
      "last_price": 17,
      "last_price_dollars": "0.17",
      "volume": 125000,
      "volume_24h": 8500,
      "result": "yes",
      "can_close_early": false,
      "open_interest": 45000,
      "notional_value": 7650,
      "notional_value_dollars": "76.50",
      "previous_yes_bid": 14,
      "previous_yes_bid_dollars": "0.14",
      "previous_yes_ask": 17,
      "previous_yes_ask_dollars": "0.17",
      "previous_price": 16,
      "previous_price_dollars": "0.16",
      "liquidity": 25000,
      "liquidity_dollars": "250.00",
      "expiration_value": "temperature",
      "tick_size": 1,
      "rules_primary": "This market will resolve to Yes if the official high temperature in New York City is 70°F or higher on January 10, 2026.",
      "rules_secondary": "Temperature data will be sourced from the National Weather Service.",
      "price_level_structure": "standard",
      "price_ranges": [
        {
          "start": "0.01",
          "end": "0.99",
          "step": "0.01"
        }
      ],
      "expected_expiration_time": "2026-01-11T05:00:00Z",
      "settlement_value": 0,
      "settlement_value_dollars": "0.00",
      "settlement_ts": "2026-01-11T05:00:00Z",
      "fee_waiver_expiration_time": "2026-01-10T00:00:00Z",
      "early_close_condition": "None",
      "strike_type": "greater",
      "floor_strike": 70,
      "cap_strike": 999,
      "functional_strike": "70",
      "custom_strike": {},
      "mve_collection_ticker": "",
      "mve_selected_legs": [],
      "primary_participant_key": "",
      "is_provisional": false
    },
    {
      "ticker": "KXHIGHNY-26JAN10-T75",
      "event_ticker": "KXHIGHNY-26JAN10",
      "market_type": "binary",
      "title": "Will the high temperature in NYC be at least 75°F on January 10, 2026?",
      "subtitle": "High temperature ≥ 75°F",
      "yes_sub_title": "High temp ≥ 75°F",
      "no_sub_title": "High temp < 75°F",
      "created_time": "2023-11-07T05:31:56Z",
      "open_time": "2023-11-07T05:31:56Z",
      "close_time": "2026-01-10T23:59:59Z",
      "expiration_time": "2026-01-11T05:00:00Z",
      "latest_expiration_time": "2026-01-11T05:00:00Z",
      "settlement_timer_seconds": 3600,
      "status": "active",
      "response_price_units": "usd_cent",
      "yes_bid": 5,
      "yes_bid_dollars": "0.05",
      "yes_ask": 8,
      "yes_ask_dollars": "0.08",
      "no_bid": 92,
      "no_bid_dollars": "0.92",
      "no_ask": 95,
      "no_ask_dollars": "0.95",
      "last_price": 7,
      "last_price_dollars": "0.07",
      "volume": 95000,
      "volume_24h": 5200,
      "result": "no",
      "can_close_early": false,
      "open_interest": 32000,
      "notional_value": 2240,
      "notional_value_dollars": "22.40",
      "previous_yes_bid": 4,
      "previous_yes_bid_dollars": "0.04",
      "previous_yes_ask": 7,
      "previous_yes_ask_dollars": "0.07",
      "previous_price": 6,
      "previous_price_dollars": "0.06",
      "liquidity": 18000,
      "liquidity_dollars": "180.00",
      "expiration_value": "temperature",
      "tick_size": 1,
      "rules_primary": "This market will resolve to Yes if the official high temperature in New York City is 75°F or higher on January 10, 2026.",
      "rules_secondary": "Temperature data will be sourced from the National Weather Service.",
      "price_level_structure": "standard",
      "price_ranges": [
        {
          "start": "0.01",
          "end": "0.99",
          "step": "0.01"
        }
      ],
      "expected_expiration_time": "2026-01-11T05:00:00Z",
      "settlement_value": 0,
      "settlement_value_dollars": "0.00",
      "settlement_ts": "2026-01-11T05:00:00Z",
      "fee_waiver_expiration_time": "2026-01-10T00:00:00Z",
      "early_close_condition": "None",
      "strike_type": "greater",
      "floor_strike": 75,
      "cap_strike": 999,
      "functional_strike": "75",
      "custom_strike": {},
      "mve_collection_ticker": "",
      "mve_selected_legs": [],
      "primary_participant_key": "",
      "is_provisional": false
    }
  ],
  "cursor": "next_page_token"
};
